################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "C:/Users/80010113/Desktop/project/fhe_hardware/verilog/vivado_project/cpet_he.xpr"
set rc [catch {
  source -notrace "C:/Users/80010113/Desktop/project/fhe_hardware/verilog/pre_sim.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"C:/Users/80010113/Desktop/project/fhe_hardware/verilog/pre_sim.tcl\""
}
close_project
