// ================================================================
// ntt_sim.cpp  —  Verilator C wrapper around the NTT Verilog model
//
// Exposes a plain C API (extern "C") so Python ctypes can call it:
//
//   void* ntt_engine_new(q, n_inv, barrett_m, fwd_table[N], inv_table[N])
//   void  ntt_engine_free(void* eng)
//   void  ntt_run(void* eng, uint64_t* coeffs, int N, int inverse)
//
// Build with:   make  (see Makefile)
// ================================================================

#include "Vntt.h"           // generated by Verilator from ntt.v
#include "verilated.h"
#include <cstdint>
#include <cstdlib>
#include <cstring>

// Required stub when not using SystemC
double sc_time_stamp() { return 0; }

// ── Per-engine context ─────────────────────────────────────────
struct NttEngine {
    VerilatedContext* ctx;
    Vntt*             model;
    uint64_t          q;
    uint64_t          n_inv;
    uint64_t          barrett_m;
    int               logn;   // N = 1 << logn
};

// ── Internal helper: advance clock one full cycle ──────────────
static void tick(NttEngine* e) {
    e->model->clk = 0; e->model->eval();
    e->model->clk = 1; e->model->eval();
}

// ── Internal helper: reset the design ─────────────────────────
static void do_reset(NttEngine* e) {
    e->model->rst_n = 0;
    e->model->start = 0;
    e->model->coeff_wr_en = 0;
    e->model->tw_wr_en    = 0;
    for (int i = 0; i < 8; i++) tick(e);
    e->model->rst_n = 1;
    tick(e);
}

// ── Internal helper: write one twiddle entry ──────────────────
static void tw_write(NttEngine* e, int addr, uint64_t val) {
    e->model->tw_wr_en   = 1;
    e->model->tw_wr_addr = (uint32_t)addr;
    e->model->tw_wr_data = val;
    tick(e);
    e->model->tw_wr_en   = 0;
}

// ──────────────────────────────────────────────────────────────
// PUBLIC API
// ──────────────────────────────────────────────────────────────

extern "C" {

// Create a new NTT engine.
//   fwd_table  : N entries (tables[0..N-1]  from _NTT_Engine)
//   inv_table  : N entries (inv_tables[0..N-1] from _NTT_Engine)
//   table_size : N
void* ntt_engine_new(uint64_t q,
                     uint64_t n_inv,
                     uint64_t barrett_m,
                     const uint64_t* fwd_table,
                     const uint64_t* inv_table,
                     int table_size)
{
    NttEngine* e = new NttEngine();
    e->ctx       = new VerilatedContext();
    e->model     = new Vntt(e->ctx, "ntt");
    e->q         = q;
    e->n_inv     = n_inv;
    e->barrett_m = barrett_m;

    // compute logn
    e->logn = 0;
    int tmp = table_size;
    while (tmp > 1) { tmp >>= 1; e->logn++; }

    // Set runtime ports that stay constant
    e->model->q     = q;
    e->model->n_inv = n_inv;
    // barrett_m is [2*Q_WIDTH-1:0] = 80 bits → VlWide<3> in Verilator
    e->model->barrett_m[0] = (uint32_t)(barrett_m);
    e->model->barrett_m[1] = (uint32_t)(barrett_m >> 32);
    e->model->barrett_m[2] = 0;

    do_reset(e);

    // Load forward twiddle table: addresses 0..N-1
    for (int i = 0; i < table_size; i++)
        tw_write(e, i, fwd_table[i]);

    // Load inverse twiddle table: addresses N..2N-1
    for (int i = 0; i < table_size; i++)
        tw_write(e, table_size + i, inv_table[i]);

    return (void*)e;
}

// Free engine resources
void ntt_engine_free(void* handle) {
    NttEngine* e = (NttEngine*)handle;
    e->model->final();
    delete e->model;
    delete e->ctx;
    delete e;
}

// Run NTT or INTT in-place on coeffs[0..N-1]
//   inverse == 0 → NTT (forward)
//   inverse == 1 → INTT (inverse)
void ntt_run(void* handle, uint64_t* coeffs, int N, int inverse) {
    NttEngine* e = (NttEngine*)handle;

    // ── Load coefficients ──────────────────────────────────────
    e->model->coeff_wr_en = 1;
    for (int i = 0; i < N; i++) {
        e->model->coeff_wr_addr = (uint32_t)i;
        e->model->coeff_wr_data = coeffs[i];
        tick(e);
    }
    e->model->coeff_wr_en = 0;
    tick(e);

    // ── Pulse start ────────────────────────────────────────────
    e->model->inverse = inverse ? 1 : 0;
    e->model->start   = 1;
    tick(e);
    e->model->start   = 0;

    // ── Wait for done ──────────────────────────────────────────
    for (int guard = 0; guard < 4*N*e->logn + 2*N + 100; guard++) {
        tick(e);
        if (e->model->done) break;
    }

    // ── Read back coefficients ─────────────────────────────────
    e->model->coeff_wr_en = 0;
    for (int i = 0; i < N; i++) {
        e->model->rd_addr = (uint32_t)i;
        tick(e);   // 1-cycle registered read
        coeffs[i] = e->model->rd_data;
    }
}

} // extern "C"
