# Auto-generated by run_sim.tcl — do not edit.
# Copies the .hex test vectors next to the xsim snapshot so
# $readmemh can locate them.
foreach f [glob -nocomplain -directory {C:/Users/80010113/Desktop/project/fhe_hardware/verilog} *.hex] {
    file copy -force $f .
}
