# ================================================================
# run_sim.tcl  —  Vivado project + xsim simulation setup
#
# Creates a Vivado project containing all RTL sources and every
# testbench, then launches behavioral simulation for the selected
# top-level testbench.
#
# Usage
# ─────
# Batch (runs tb_rns_hash_verifier by default):
#   cd verilog/
#   vivado -mode batch -source run_sim.tcl
#
# Batch with a different testbench:
#   vivado -mode batch -source run_sim.tcl \
#          -tclargs tb_cipher_hash
#
# Interactive (from Vivado Tcl console):
#   source run_sim.tcl
#   # then pick a different top and re-run:
#   sim_run tb_rns_ntt
#
# Available testbench tops
# ────────────────────────
#   tb_rns_hash_verifier        (default) — 2-lane RNS hash verification
#   tb_rns_ntt                            — 2-lane RNS NTT / INTT
#   tb_ntt_mont                           — Montgomery NTT core (LOGN=13)
#   tb_cipher_hash                        — single-lane cipher hash
#   tb_hash_verifier                      — single-lane hash verifier
#   tb_hash_verifier_schoolbook           — schoolbook hash verifier
#   tb_poly_mul_schoolbook                — schoolbook poly multiply
#
# Notes
# ─────
# • The .hex test vector files must be in verilog/ before running.
#   Generate them with:  cd src/ && python ../verilog/gen_test_vectors.py
#                                   python ../verilog/gen_rns_ntt_vectors.py
#                                   python ../verilog/gen_rns_hv_vectors.py
#   tb_ntt_mont needs its own vectors at the matching LOGN:
#                                   python ../verilog/gen_ntt_mont_vectors.py 13
# • xsim runs in <project>/cpet_he_sim.sim/.../xsim/ by default.
#   A pre-simulation hook (pre_sim.tcl) cds to verilog/ so every
#   $readmemh call resolves correctly without touching the testbenches.
# • Schoolbook poly-mul is extremely slow at N=8192 (~268 M cycles).
#   Run it only if you specifically need the cycle-count comparison.
# ================================================================

# ── Resolve verilog/ directory regardless of invocation path ─────
set VDIR [file dirname [file normalize [info script]]]

# ── Parse optional tclargs ────────────────────────────────────────
set TOP_DEFAULT "tb_rns_hash_verifier"
if { [llength $argv] > 0 } {
    set TOP [lindex $argv 0]
} else {
    set TOP $TOP_DEFAULT
}

# Validate
set VALID_TOPS {
    tb_rns_hash_verifier
    tb_rns_ntt
    tb_ntt_mont
    tb_cipher_hash
    tb_hash_verifier
    tb_hash_verifier_schoolbook
    tb_poly_mul_schoolbook
}
if { [lsearch $VALID_TOPS $TOP] < 0 } {
    puts "ERROR: Unknown testbench '$TOP'."
    puts "Valid choices: $VALID_TOPS"
    return
}

# ── Create project ────────────────────────────────────────────────
create_project cpet_he_sim $VDIR/vivado_project \
    -part xc7a100tcsg324-1 -force

set_property target_language    Verilog [current_project]
set_property simulator_language Verilog [current_project]

# ── RTL design sources ────────────────────────────────────────────
add_files -norecurse [list \
    $VDIR/ntt.v                      \
    $VDIR/ntt_mont.v                 \
    $VDIR/poly_mul.v                 \
    $VDIR/poly_add.v                 \
    $VDIR/cipher_hash.v              \
    $VDIR/hash_verifier.v            \
    $VDIR/rns_ntt.v                  \
    $VDIR/rns_hash_verifier.v        \
    $VDIR/poly_mul_schoolbook.v      \
    $VDIR/cipher_hash_schoolbook.v   \
    $VDIR/hash_verifier_schoolbook.v \
]
update_compile_order -fileset sources_1

# ── Simulation sources (all testbenches in one fileset) ───────────
add_files -fileset sim_1 -norecurse [list \
    $VDIR/tb_rns_hash_verifier.v         \
    $VDIR/tb_rns_ntt.v                   \
    $VDIR/tb_ntt_mont.v                  \
    $VDIR/tb_cipher_hash.v               \
    $VDIR/tb_hash_verifier.v             \
    $VDIR/tb_hash_verifier_schoolbook.v  \
    $VDIR/tb_poly_mul_schoolbook.v       \
]
update_compile_order -fileset sim_1

# ── Pre-simulation hook: stage the .hex vectors for $readmemh ────
# xsim runs in the project sim directory; the hex files live in verilog/.
# xsim resolves $readmemh against the xsim.dir location rather than the
# Tcl working directory, so `cd` is not enough — copy the vectors in.
set PRE_SIM $VDIR/pre_sim.tcl
set fh [open $PRE_SIM w]
puts $fh "# Auto-generated by run_sim.tcl — do not edit."
puts $fh "# Copies the .hex test vectors next to the xsim snapshot so"
puts $fh "# \$readmemh can locate them."
puts $fh "foreach f \[glob -nocomplain -directory {$VDIR} *.hex\] {"
puts $fh "    file copy -force \$f ."
puts $fh "}"
close $fh

# NOTE: the property is xsim.compile.tcl.pre — there is NO xsim.simulate.tcl.pre
# in Vivado. set_property -name silently accepts an unknown name as a user
# property, so a wrong name here fails without any error.
set_property -name {xsim.compile.tcl.pre} \
             -value $PRE_SIM \
             -objects [get_filesets sim_1]

# Run for as long as the testbench needs ($finish terminates it).
set_property -name {xsim.simulate.runtime} -value {-all} -objects [get_filesets sim_1]

# ── Helper proc: switch top and launch simulation ─────────────────
proc sim_run { top } {
    set_property top      $top           [get_filesets sim_1]
    set_property top_lib  xil_defaultlib [get_filesets sim_1]
    puts "\n>>> Launching simulation: $top\n"
    # xsim.simulate.runtime is {-all}, so launch_simulation already runs to
    # $finish. Do NOT `run all` afterwards — it resumes the finished sim and
    # trips the testbench's hard-timeout watchdog with a bogus FATAL.
    launch_simulation
}

# ── Set the chosen top and launch ─────────────────────────────────
sim_run $TOP

puts ""
puts "================================================================"
puts "  Simulation complete: $TOP"
puts ""
puts "  To run a different testbench from the Tcl console:"
foreach t $VALID_TOPS {
    puts "    sim_run $t"
}
puts "================================================================"
