`timescale 1ns/1ps
// ================================================================
// tb_cipher_hash.v  —  Vivado testbench for cipher_hash module
//
// Loads test vectors from hex files generated by gen_test_vectors.py.
// Computes H(c1) and compares against expected output.
//
// Usage in Vivado:
//   1. Run: cd src/ && python ../verilog/gen_test_vectors.py
//   2. Add design sources: cipher_hash.v, poly_mul.v, poly_add.v, ntt.v
//   3. Add simulation source: tb_cipher_hash.v
//   4. Run Behavioral Simulation
// ================================================================
module tb_cipher_hash;

    // ── Parameters ──────────────────────────────────────────────
    localparam LOGN    = 13;
    localparam Q_WIDTH = 60;
    localparam CT_SIZE = 3;
    localparam integer N = 1 << LOGN;   // 8192

    // Timeout: each poly_mul takes ~2*N*LOGN+2*N cycles,
    // cipher_hash does up to 4 poly_muls + 2 poly_adds for 3-component ct
    localparam integer MAX_CYCLES = 2000000;

    // ── Clock and reset ─────────────────────────────────────────
    reg clk;
    reg rst_n;

    initial clk = 0;
    always #5 clk = ~clk;  // 100 MHz

    // ── DUT signals ─────────────────────────────────────────────
    reg  [Q_WIDTH-1:0]  q;
    reg  [Q_WIDTH-1:0]  n_inv;
    reg  [2*Q_WIDTH-1:0] barrett_m_val;
    reg  [1:0]          ct_sel;
    reg                 ct_wr_en;
    reg  [LOGN-1:0]     ct_wr_addr;
    reg  [Q_WIDTH-1:0]  ct_wr_data;
    reg                 r_wr_en;
    reg  [LOGN-1:0]     r_wr_addr;
    reg  [Q_WIDTH-1:0]  r_wr_data;
    reg                 tw_wr_en;
    reg  [LOGN:0]       tw_wr_addr;
    reg  [Q_WIDTH-1:0]  tw_wr_data;
    reg  [1:0]          ct_count;
    reg                 start;
    reg  [LOGN-1:0]     rd_addr;
    wire [Q_WIDTH-1:0]  rd_data;
    wire                done;

    // ── DUT instantiation ───────────────────────────────────────
    cipher_hash #(
        .LOGN    (LOGN),
        .Q_WIDTH (Q_WIDTH),
        .CT_SIZE (CT_SIZE)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .q          (q),
        .n_inv      (n_inv),
        .barrett_m  (barrett_m_val),
        .ct_sel     (ct_sel),
        .ct_wr_en   (ct_wr_en),
        .ct_wr_addr (ct_wr_addr),
        .ct_wr_data (ct_wr_data),
        .r_wr_en    (r_wr_en),
        .r_wr_addr  (r_wr_addr),
        .r_wr_data  (r_wr_data),
        .tw_wr_en   (tw_wr_en),
        .tw_wr_addr (tw_wr_addr),
        .tw_wr_data (tw_wr_data),
        .ct_count   (ct_count),
        .start      (start),
        .rd_addr    (rd_addr),
        .rd_data    (rd_data),
        .done       (done)
    );

    // ── Test vector memories ────────────────────────────────────
    reg [2*Q_WIDTH-1:0] tv_params    [0:5];
    reg [Q_WIDTH-1:0] tv_twiddles_fwd [0:N-1];
    reg [Q_WIDTH-1:0] tv_twiddles_inv [0:N-1];
    reg [Q_WIDTH-1:0] tv_r           [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_0        [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_1        [0:N-1];
    reg [Q_WIDTH-1:0] tv_h1          [0:N-1];

    // ── Result storage ──────────────────────────────────────────
    reg [Q_WIDTH-1:0] result [0:N-1];

    // ── Counters ────────────────────────────────────────────────
    integer i;
    integer cycle_count;
    integer mismatch_count;

    // ── Main test sequence ──────────────────────────────────────
    initial begin
        $display("================================================================");
        $display("  tb_cipher_hash — Vivado Behavioral Simulation");
        $display("================================================================");

        // Load test vectors
        $readmemh("tv_params.hex",       tv_params);
        $readmemh("tv_twiddles_fwd.hex", tv_twiddles_fwd);
        $readmemh("tv_twiddles_inv.hex", tv_twiddles_inv);
        $readmemh("tv_r.hex",            tv_r);
        $readmemh("tv_c1_0.hex",         tv_c1_0);
        $readmemh("tv_c1_1.hex",         tv_c1_1);
        $readmemh("tv_h1.hex",           tv_h1);

        // Extract parameters
        q             = tv_params[0][Q_WIDTH-1:0];
        n_inv         = tv_params[1][Q_WIDTH-1:0];
        ct_count      = tv_params[2][1:0];  // c1_count
        barrett_m_val = tv_params[5];

        $display("  q          = %0d (0x%015h)", q, q);
        $display("  n_inv      = %0d", n_inv);
        $display("  barrett_m  = %0d", barrett_m_val);
        $display("  ct_count   = %0d", ct_count);
        $display("");

        // ── Reset ───────────────────────────────────────────────
        rst_n     = 0;
        start     = 0;
        ct_wr_en  = 0;
        r_wr_en   = 0;
        tw_wr_en  = 0;
        rd_addr   = 0;
        repeat (10) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ── Load twiddle tables ─────────────────────────────────
        $display("  [%0t] Loading twiddle tables...", $time);
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = i[LOGN:0];
            tw_wr_data = tv_twiddles_fwd[i];
            @(posedge clk);
        end
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = N[LOGN:0] + i[LOGN:0];
            tw_wr_data = tv_twiddles_inv[i];
            @(posedge clk);
        end
        tw_wr_en = 0;
        @(posedge clk);

        // ── Load r polynomial ───────────────────────────────────
        $display("  [%0t] Loading r polynomial...", $time);
        for (i = 0; i < N; i = i + 1) begin
            r_wr_en   = 1;
            r_wr_addr = i[LOGN-1:0];
            r_wr_data = tv_r[i];
            @(posedge clk);
        end
        r_wr_en = 0;
        @(posedge clk);

        // ── Load c1 component 0 ─────────────────────────────────
        $display("  [%0t] Loading c1[0]...", $time);
        for (i = 0; i < N; i = i + 1) begin
            ct_wr_en   = 1;
            ct_sel     = 2'd0;
            ct_wr_addr = i[LOGN-1:0];
            ct_wr_data = tv_c1_0[i];
            @(posedge clk);
        end
        ct_wr_en = 0;
        @(posedge clk);

        // ── Load c1 component 1 ─────────────────────────────────
        $display("  [%0t] Loading c1[1]...", $time);
        for (i = 0; i < N; i = i + 1) begin
            ct_wr_en   = 1;
            ct_sel     = 2'd1;
            ct_wr_addr = i[LOGN-1:0];
            ct_wr_data = tv_c1_1[i];
            @(posedge clk);
        end
        ct_wr_en = 0;
        @(posedge clk);

        // ── Start cipher_hash ───────────────────────────────────
        $display("  [%0t] Starting cipher_hash computation...", $time);
        start = 1;
        @(posedge clk);
        start = 0;

        // ── Wait for done ───────────────────────────────────────
        cycle_count = 0;
        while (!done && cycle_count < MAX_CYCLES) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end

        if (!done) begin
            $display("  ERROR: Timeout after %0d cycles!", MAX_CYCLES);
            $finish;
        end
        $display("  [%0t] Done after %0d cycles.", $time, cycle_count);

        // ── Read results (1-cycle registered read latency) ──────
        $display("  [%0t] Reading result...", $time);
        for (i = 0; i < N; i = i + 1) begin
            rd_addr = i[LOGN-1:0];
            @(posedge clk);   // rd_data <= mem_h[i] scheduled in NBA
            #1;               // let NBA complete
            result[i] = rd_data;
        end

        // ── Compare results ─────────────────────────────────────
        $display("  [%0t] Comparing results...", $time);
        mismatch_count = 0;
        for (i = 0; i < N; i = i + 1) begin
            if (result[i] !== tv_h1[i]) begin
                mismatch_count = mismatch_count + 1;
                if (mismatch_count <= 10) begin
                    $display("    MISMATCH at [%0d]: got 0x%010h, expected 0x%010h",
                             i, result[i], tv_h1[i]);
                end
            end
        end

        // ── Report ──────────────────────────────────────────────
        $display("");
        $display("================================================================");
        if (mismatch_count == 0) begin
            $display("  PASS — All %0d coefficients match!", N);
        end else begin
            $display("  FAIL — %0d / %0d mismatches", mismatch_count, N);
        end
        $display("================================================================");

        $finish;
    end

    // ── Timeout watchdog ────────────────────────────────────────
    initial begin
        #(MAX_CYCLES * 10 * 2);  // 10ns per cycle * 2 for safety
        $display("  FATAL: Simulation timeout!");
        $finish;
    end

endmodule
