`timescale 1ns/1ps
// ================================================================
// tb_hash_verifier.v  —  Vivado testbench for hash_verifier module
//
// Loads test vectors from hex files generated by gen_test_vectors.py.
// Verifies that H(c3) == H(c1)*H(c2) + H(c2) → valid=1.
//
// 3-phase load protocol:
//   1. Load c1 → start → wait ready
//   2. Load c2 → start → wait ready
//   3. Load c3 → start → wait done
// ================================================================
module tb_hash_verifier;

    // ── Parameters ──────────────────────────────────────────────
    localparam LOGN    = 13;
    localparam Q_WIDTH = 40;
    localparam CT_SIZE = 3;
    localparam integer N = 1 << LOGN;   // 8192

    localparam integer MAX_CYCLES = 30000000;

    // ── Clock and reset ─────────────────────────────────────────
    reg clk;
    reg rst_n;

    initial clk = 0;
    always #5 clk = ~clk;  // 100 MHz

    // ── DUT signals ─────────────────────────────────────────────
    reg  [Q_WIDTH-1:0]   q;
    reg  [Q_WIDTH-1:0]   n_inv;
    reg  [2*Q_WIDTH-1:0] barrett_m_val;
    reg  [1:0]           ct_sel;
    reg                  ct_wr_en;
    reg  [LOGN-1:0]      ct_wr_addr;
    reg  [Q_WIDTH-1:0]   ct_wr_data;
    reg                  r_wr_en;
    reg  [LOGN-1:0]      r_wr_addr;
    reg  [Q_WIDTH-1:0]   r_wr_data;
    reg                  tw_wr_en;
    reg  [LOGN:0]        tw_wr_addr;
    reg  [Q_WIDTH-1:0]   tw_wr_data;
    reg  [1:0]           c1_count;
    reg  [1:0]           c2_count;
    reg  [1:0]           c3_count;
    reg                  start;
    wire                 ready;
    wire                 done;
    wire                 valid;

    // ── DUT instantiation ───────────────────────────────────────
    hash_verifier #(
        .LOGN    (LOGN),
        .Q_WIDTH (Q_WIDTH),
        .CT_SIZE (CT_SIZE)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .q          (q),
        .n_inv      (n_inv),
        .barrett_m  (barrett_m_val),
        .ct_sel     (ct_sel),
        .ct_wr_en   (ct_wr_en),
        .ct_wr_addr (ct_wr_addr),
        .ct_wr_data (ct_wr_data),
        .r_wr_en    (r_wr_en),
        .r_wr_addr  (r_wr_addr),
        .r_wr_data  (r_wr_data),
        .tw_wr_en   (tw_wr_en),
        .tw_wr_addr (tw_wr_addr),
        .tw_wr_data (tw_wr_data),
        .c1_count   (c1_count),
        .c2_count   (c2_count),
        .c3_count   (c3_count),
        .start      (start),
        .ready      (ready),
        .done       (done),
        .valid      (valid)
    );

    // ── Test vector memories ────────────────────────────────────
    reg [2*Q_WIDTH-1:0] tv_params     [0:5];
    reg [Q_WIDTH-1:0] tv_twiddles_fwd [0:N-1];
    reg [Q_WIDTH-1:0] tv_twiddles_inv [0:N-1];
    reg [Q_WIDTH-1:0] tv_r            [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c2_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c2_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_2         [0:N-1];

    integer i;
    integer cycle_count;

    // ── Task: load one ciphertext component into cipher_hash ────
    task load_ct_component;
        input [1:0]  comp;     // ct_sel: component index
        input integer mem_sel; // which test-vector memory (0-6)
        begin
            for (i = 0; i < N; i = i + 1) begin
                ct_wr_en   = 1;
                ct_sel     = comp;
                ct_wr_addr = i[LOGN-1:0];
                case (mem_sel)
                    0: ct_wr_data = tv_c1_0[i];
                    1: ct_wr_data = tv_c1_1[i];
                    2: ct_wr_data = tv_c2_0[i];
                    3: ct_wr_data = tv_c2_1[i];
                    4: ct_wr_data = tv_c3_0[i];
                    5: ct_wr_data = tv_c3_1[i];
                    6: ct_wr_data = tv_c3_2[i];
                    default: ct_wr_data = 0;
                endcase
                @(posedge clk);
            end
            ct_wr_en = 0;
            @(posedge clk);
        end
    endtask

    // ── Main test sequence ──────────────────────────────────────
    initial begin
        $display("================================================================");
        $display("  tb_hash_verifier — Vivado Behavioral Simulation");
        $display("================================================================");

        $readmemh("tv_params.hex",       tv_params);
        $readmemh("tv_twiddles_fwd.hex", tv_twiddles_fwd);
        $readmemh("tv_twiddles_inv.hex", tv_twiddles_inv);
        $readmemh("tv_r.hex",            tv_r);
        $readmemh("tv_c1_0.hex",         tv_c1_0);
        $readmemh("tv_c1_1.hex",         tv_c1_1);
        $readmemh("tv_c2_0.hex",         tv_c2_0);
        $readmemh("tv_c2_1.hex",         tv_c2_1);
        $readmemh("tv_c3_0.hex",         tv_c3_0);
        $readmemh("tv_c3_1.hex",         tv_c3_1);
        $readmemh("tv_c3_2.hex",         tv_c3_2);

        q             = tv_params[0][Q_WIDTH-1:0];
        n_inv         = tv_params[1][Q_WIDTH-1:0];
        c1_count      = tv_params[2][1:0];
        c2_count      = tv_params[3][1:0];
        c3_count      = tv_params[4][1:0];
        barrett_m_val = tv_params[5];

        $display("  q          = %0d (0x%010h)", q, q);
        $display("  n_inv      = %0d", n_inv);
        $display("  barrett_m  = %0d", barrett_m_val);
        $display("  c1_count   = %0d", c1_count);
        $display("  c2_count   = %0d", c2_count);
        $display("  c3_count   = %0d", c3_count);
        $display("");

        // ── Reset ───────────────────────────────────────────────
        rst_n    = 0;
        start    = 0;
        ct_wr_en = 0;
        r_wr_en  = 0;
        tw_wr_en = 0;
        repeat (10) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ── Load twiddle tables ─────────────────────────────────
        $display("  [%0t] Loading twiddle tables (2 x %0d)...", $time, N);
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = i[LOGN:0];
            tw_wr_data = tv_twiddles_fwd[i];
            @(posedge clk);
        end
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = N[LOGN:0] + i[LOGN:0];
            tw_wr_data = tv_twiddles_inv[i];
            @(posedge clk);
        end
        tw_wr_en = 0;
        @(posedge clk);

        // ── Load r polynomial ───────────────────────────────────
        $display("  [%0t] Loading r polynomial...", $time);
        for (i = 0; i < N; i = i + 1) begin
            r_wr_en   = 1;
            r_wr_addr = i[LOGN-1:0];
            r_wr_data = tv_r[i];
            @(posedge clk);
        end
        r_wr_en = 0;
        @(posedge clk);

        // ── Phase 1: load c1, trigger h1 ────────────────────────
        $display("  [%0t] Loading c1[0]...", $time);
        load_ct_component(2'd0, 0);
        $display("  [%0t] Loading c1[1]...", $time);
        load_ct_component(2'd1, 1);

        $display("  [%0t] Starting h1 computation...", $time);
        start = 1; @(posedge clk); start = 0;

        while (!ready) @(posedge clk);

        // ── Phase 2: load c2, trigger h2 ────────────────────────
        $display("  [%0t] Loading c2[0]...", $time);
        load_ct_component(2'd0, 2);
        $display("  [%0t] Loading c2[1]...", $time);
        load_ct_component(2'd1, 3);

        $display("  [%0t] Starting h2 computation...", $time);
        start = 1; @(posedge clk); start = 0;

        while (!ready) @(posedge clk);

        // ── Phase 3: load c3, trigger h3 + verify ───────────────
        $display("  [%0t] Loading c3[0]...", $time);
        load_ct_component(2'd0, 4);
        $display("  [%0t] Loading c3[1]...", $time);
        load_ct_component(2'd1, 5);
        $display("  [%0t] Loading c3[2]...", $time);
        load_ct_component(2'd2, 6);

        $display("");
        $display("  [%0t] Starting hash verification...", $time);
        start = 1; @(posedge clk); start = 0;

        // ── Wait for done ───────────────────────────────────────
        cycle_count = 0;
        while (!done && cycle_count < MAX_CYCLES) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end

        if (!done) begin
            $display("  ERROR: Timeout after %0d cycles!", MAX_CYCLES);
            $display("================================================================");
            $finish;
        end

        $display("  [%0t] Done after %0d cycles.", $time, cycle_count);

        $display("");
        $display("================================================================");
        if (valid) begin
            $display("  PASS \xe2\x80\x94 valid = 1");
            $display("  H(c3) == H(c1)*H(c2) + H(c2) verified in hardware!");
        end else begin
            $display("  FAIL \xe2\x80\x94 valid = 0");
            $display("  Hash verification FAILED. Hashes do not match.");
        end
        $display("  Total simulation cycles: %0d", cycle_count);
        $display("================================================================");

        $finish;
    end

    // ── Timeout watchdog ────────────────────────────────────────
    initial begin
        #(MAX_CYCLES * 10 * 2);
        $display("  FATAL: Simulation timeout!");
        $finish;
    end

endmodule
