`timescale 1ns/1ps
// ================================================================
// tb_hash_verifier.v  —  Vivado testbench for hash_verifier module
//
// Loads test vectors from hex files generated by gen_test_vectors.py.
// Verifies that H(c3) == H(c1)*H(c2) + H(c2) → valid=1.
//
// Usage in Vivado:
//   1. Run: cd src/ && python ../verilog/gen_test_vectors.py
//   2. Add design sources: hash_verifier.v, cipher_hash.v,
//                          poly_mul.v, poly_add.v, ntt.v
//   3. Add simulation source: tb_hash_verifier.v
//   4. Run Behavioral Simulation
// ================================================================
module tb_hash_verifier;

    // ── Parameters ──────────────────────────────────────────────
    localparam LOGN    = 13;
    localparam Q_WIDTH = 40;
    localparam CT_SIZE = 3;
    localparam integer N = 1 << LOGN;   // 8192

    // Timeout: hash_verifier runs 3 cipher_hashes + 1 poly_mul + 1 poly_add + compare
    // Each cipher_hash with 3 components: ~4 poly_muls + 2 poly_adds
    // Total: ~15 poly_muls + ~8 poly_adds ≈ 15*(2*N*LOGN+2*N) + small
    localparam integer MAX_CYCLES = 20000000;

    // ── Clock and reset ─────────────────────────────────────────
    reg clk;
    reg rst_n;

    initial clk = 0;
    always #5 clk = ~clk;  // 100 MHz

    // ── DUT signals ─────────────────────────────────────────────
    reg  [Q_WIDTH-1:0]  q;
    reg  [Q_WIDTH-1:0]  n_inv;
    reg  [2*Q_WIDTH-1:0] barrett_m_val;
    reg  [1:0]          ct_id;
    reg  [1:0]          ct_sel;
    reg                 ct_wr_en;
    reg  [LOGN-1:0]     ct_wr_addr;
    reg  [Q_WIDTH-1:0]  ct_wr_data;
    reg                 r_wr_en;
    reg  [LOGN-1:0]     r_wr_addr;
    reg  [Q_WIDTH-1:0]  r_wr_data;
    reg                 tw_wr_en;
    reg  [LOGN:0]       tw_wr_addr;
    reg  [Q_WIDTH-1:0]  tw_wr_data;
    reg  [1:0]          c1_count;
    reg  [1:0]          c2_count;
    reg  [1:0]          c3_count;
    reg                 start;
    wire                done;
    wire                valid;

    // ── DUT instantiation ───────────────────────────────────────
    hash_verifier #(
        .LOGN    (LOGN),
        .Q_WIDTH (Q_WIDTH),
        .CT_SIZE (CT_SIZE)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .q          (q),
        .n_inv      (n_inv),
        .barrett_m  (barrett_m_val),
        .ct_id      (ct_id),
        .ct_sel     (ct_sel),
        .ct_wr_en   (ct_wr_en),
        .ct_wr_addr (ct_wr_addr),
        .ct_wr_data (ct_wr_data),
        .r_wr_en    (r_wr_en),
        .r_wr_addr  (r_wr_addr),
        .r_wr_data  (r_wr_data),
        .tw_wr_en   (tw_wr_en),
        .tw_wr_addr (tw_wr_addr),
        .tw_wr_data (tw_wr_data),
        .c1_count   (c1_count),
        .c2_count   (c2_count),
        .c3_count   (c3_count),
        .start      (start),
        .done       (done),
        .valid      (valid)
    );

    // ── Test vector memories ────────────────────────────────────
    reg [2*Q_WIDTH-1:0] tv_params     [0:5];
    reg [Q_WIDTH-1:0] tv_twiddles_fwd [0:N-1];
    reg [Q_WIDTH-1:0] tv_twiddles_inv [0:N-1];
    reg [Q_WIDTH-1:0] tv_r            [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c1_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c2_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c2_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_0         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_1         [0:N-1];
    reg [Q_WIDTH-1:0] tv_c3_2         [0:N-1];

    // ── Counters ────────────────────────────────────────────────
    integer i;
    integer cycle_count;

    // ── Task: load one ciphertext component ─────────────────────
    task load_ct_component;
        input [1:0] id;       // ct_id: 0=c1, 1=c2, 2=c3
        input [1:0] comp;     // component index
        input integer mem_sel; // which memory to read from (0-6)
        begin
            for (i = 0; i < N; i = i + 1) begin
                ct_wr_en   = 1;
                ct_id      = id;
                ct_sel     = comp;
                ct_wr_addr = i[LOGN-1:0];
                case (mem_sel)
                    0: ct_wr_data = tv_c1_0[i];
                    1: ct_wr_data = tv_c1_1[i];
                    2: ct_wr_data = tv_c2_0[i];
                    3: ct_wr_data = tv_c2_1[i];
                    4: ct_wr_data = tv_c3_0[i];
                    5: ct_wr_data = tv_c3_1[i];
                    6: ct_wr_data = tv_c3_2[i];
                    default: ct_wr_data = 0;
                endcase
                @(posedge clk);
            end
            ct_wr_en = 0;
            @(posedge clk);
        end
    endtask

    // ── Main test sequence ──────────────────────────────────────
    initial begin
        $display("================================================================");
        $display("  tb_hash_verifier — Vivado Behavioral Simulation");
        $display("================================================================");

        // Load test vectors
        $readmemh("tv_params.hex",       tv_params);
        $readmemh("tv_twiddles_fwd.hex", tv_twiddles_fwd);
        $readmemh("tv_twiddles_inv.hex", tv_twiddles_inv);
        $readmemh("tv_r.hex",            tv_r);
        $readmemh("tv_c1_0.hex",         tv_c1_0);
        $readmemh("tv_c1_1.hex",         tv_c1_1);
        $readmemh("tv_c2_0.hex",         tv_c2_0);
        $readmemh("tv_c2_1.hex",         tv_c2_1);
        $readmemh("tv_c3_0.hex",         tv_c3_0);
        $readmemh("tv_c3_1.hex",         tv_c3_1);
        $readmemh("tv_c3_2.hex",         tv_c3_2);

        // Extract parameters
        q             = tv_params[0][Q_WIDTH-1:0];
        n_inv         = tv_params[1][Q_WIDTH-1:0];
        c1_count      = tv_params[2][1:0];
        c2_count      = tv_params[3][1:0];
        c3_count      = tv_params[4][1:0];
        barrett_m_val = tv_params[5];

        $display("  q          = %0d (0x%010h)", q, q);
        $display("  n_inv      = %0d", n_inv);
        $display("  barrett_m  = %0d", barrett_m_val);
        $display("  c1_count   = %0d", c1_count);
        $display("  c2_count   = %0d", c2_count);
        $display("  c3_count   = %0d", c3_count);
        $display("");

        // ── Reset ───────────────────────────────────────────────
        rst_n     = 0;
        start     = 0;
        ct_wr_en  = 0;
        r_wr_en   = 0;
        tw_wr_en  = 0;
        repeat (10) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ── Load twiddle tables ─────────────────────────────────
        $display("  [%0t] Loading twiddle tables (2 x %0d)...", $time, N);
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = i[LOGN:0];
            tw_wr_data = tv_twiddles_fwd[i];
            @(posedge clk);
        end
        for (i = 0; i < N; i = i + 1) begin
            tw_wr_en   = 1;
            tw_wr_addr = N[LOGN:0] + i[LOGN:0];
            tw_wr_data = tv_twiddles_inv[i];
            @(posedge clk);
        end
        tw_wr_en = 0;
        @(posedge clk);

        // ── Load r polynomial ───────────────────────────────────
        $display("  [%0t] Loading r polynomial...", $time);
        for (i = 0; i < N; i = i + 1) begin
            r_wr_en   = 1;
            r_wr_addr = i[LOGN-1:0];
            r_wr_data = tv_r[i];
            @(posedge clk);
        end
        r_wr_en = 0;
        @(posedge clk);

        // ── Load c1 (2 components) ──────────────────────────────
        $display("  [%0t] Loading c1[0]...", $time);
        load_ct_component(2'd0, 2'd0, 0);   // ct_id=0, comp=0, mem=tv_c1_0
        $display("  [%0t] Loading c1[1]...", $time);
        load_ct_component(2'd0, 2'd1, 1);   // ct_id=0, comp=1, mem=tv_c1_1

        // ── Load c2 (2 components) ──────────────────────────────
        $display("  [%0t] Loading c2[0]...", $time);
        load_ct_component(2'd1, 2'd0, 2);   // ct_id=1, comp=0, mem=tv_c2_0
        $display("  [%0t] Loading c2[1]...", $time);
        load_ct_component(2'd1, 2'd1, 3);   // ct_id=1, comp=1, mem=tv_c2_1

        // ── Load c3 (3 components) ──────────────────────────────
        $display("  [%0t] Loading c3[0]...", $time);
        load_ct_component(2'd2, 2'd0, 4);   // ct_id=2, comp=0, mem=tv_c3_0
        $display("  [%0t] Loading c3[1]...", $time);
        load_ct_component(2'd2, 2'd1, 5);   // ct_id=2, comp=1, mem=tv_c3_1
        $display("  [%0t] Loading c3[2]...", $time);
        load_ct_component(2'd2, 2'd2, 6);   // ct_id=2, comp=2, mem=tv_c3_2

        // ── Start verification ──────────────────────────────────
        $display("");
        $display("  [%0t] Starting hash verification...", $time);
        start = 1;
        @(posedge clk);
        start = 0;

        // ── Wait for done ───────────────────────────────────────
        cycle_count = 0;
        while (!done && cycle_count < MAX_CYCLES) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end

        if (!done) begin
            $display("  ERROR: Timeout after %0d cycles!", MAX_CYCLES);
            $display("================================================================");
            $finish;
        end

        $display("  [%0t] Done after %0d cycles.", $time, cycle_count);

        // ── Check result ────────────────────────────────────────
        $display("");
        $display("================================================================");
        if (valid) begin
            $display("  PASS — valid = 1");
            $display("  H(c3) == H(c1)*H(c2) + H(c2) verified in hardware!");
        end else begin
            $display("  FAIL — valid = 0");
            $display("  Hash verification FAILED. Hashes do not match.");
        end
        $display("  Total simulation cycles: %0d", cycle_count);
        $display("================================================================");

        $finish;
    end

    // ── Timeout watchdog ────────────────────────────────────────
    initial begin
        #(MAX_CYCLES * 10 * 2);  // 10ns per cycle * 2 for safety
        $display("  FATAL: Simulation timeout!");
        $finish;
    end

endmodule
