`timescale 1ns/1ps
// ================================================================
// tb_rns_ntt.v — Testbench for rns_ntt (parallel RNS NTT)
//
// Loads test vectors generated by gen_rns_ntt_vectors.py and
// compares hardware output against SW-reference expected values
// for BOTH prime lanes.
//
// Two checks:
//   1. NTT:  HW_NTT(input)     == tv_rns_ntt_lane{i}.hex
//   2. INTT: HW_INTT(NTT_out)  == tv_rns_intt_lane{i}.hex
//
// Usage (Vivado sim or icarus):
//   iverilog -o tb_rns_ntt tb_rns_ntt.v rns_ntt.v ntt.v && vvp tb_rns_ntt
//
// Parameters must match gen_rns_ntt_vectors.py arguments:
//   LOGN=4, Q_WIDTH=60, N_PRIMES=2
// ================================================================
module tb_rns_ntt;

    // ── Match compiled parameters ─────────────────────────────────
    parameter integer LOGN     = 4;
    parameter integer Q_WIDTH  = 60;
    parameter integer N_PRIMES = 2;
    parameter integer SEL_W    = 1;
    parameter integer N        = 1 << LOGN;

    // ── Clock & reset ─────────────────────────────────────────────
    reg clk;
    reg rst_n;
    always #5 clk = ~clk;    // 100 MHz

    // ── DUT ports ─────────────────────────────────────────────────
    reg  [N_PRIMES*Q_WIDTH-1:0]      q_all;
    reg  [N_PRIMES*Q_WIDTH-1:0]      n_inv_all;
    reg  [N_PRIMES*64-1:0]           q_neg_inv_all;
    reg  [SEL_W-1:0]                 lane_sel;
    reg                              coeff_wr_en;
    reg  [LOGN-1:0]                  coeff_wr_addr;
    reg  [Q_WIDTH-1:0]               coeff_wr_data;
    reg  [SEL_W-1:0]                 tw_lane_sel;
    reg                              tw_wr_en;
    reg  [LOGN:0]                    tw_wr_addr;
    reg  [Q_WIDTH-1:0]               tw_wr_data;
    reg                              start;
    reg                              inverse;
    reg  [SEL_W-1:0]                 rd_lane;
    reg  [LOGN-1:0]                  rd_addr;
    wire [Q_WIDTH-1:0]               rd_data;
    wire [N_PRIMES-1:0]              lane_done;
    wire                             done;

    // ── DUT ───────────────────────────────────────────────────────
    rns_ntt #(
        .LOGN     (LOGN),
        .Q_WIDTH  (Q_WIDTH),
        .N_PRIMES (N_PRIMES),
        .SEL_W    (SEL_W)
    ) dut (
        .clk           (clk),
        .rst_n         (rst_n),
        .q_all         (q_all),
        .n_inv_all     (n_inv_all),
        .q_neg_inv_all (q_neg_inv_all),
        .lane_sel      (lane_sel),
        .coeff_wr_en   (coeff_wr_en),
        .coeff_wr_addr (coeff_wr_addr),
        .coeff_wr_data (coeff_wr_data),
        .tw_lane_sel   (tw_lane_sel),
        .tw_wr_en      (tw_wr_en),
        .tw_wr_addr    (tw_wr_addr),
        .tw_wr_data    (tw_wr_data),
        .start         (start),
        .inverse       (inverse),
        .rd_lane       (rd_lane),
        .rd_addr       (rd_addr),
        .rd_data       (rd_data),
        .lane_done     (lane_done),
        .done          (done)
    );

    // ── Test vector memories ──────────────────────────────────────
    // params: [0]=q, [1]=n_inv_mont, [2]=q_neg_inv  (stored at 2*Q_WIDTH bits)
    reg [2*Q_WIDTH-1:0] params0 [0:2];
    reg [2*Q_WIDTH-1:0] params1 [0:2];

    reg [Q_WIDTH-1:0]   tw_fwd0 [0:N-1];
    reg [Q_WIDTH-1:0]   tw_inv0 [0:N-1];
    reg [Q_WIDTH-1:0]   tw_fwd1 [0:N-1];
    reg [Q_WIDTH-1:0]   tw_inv1 [0:N-1];

    reg [Q_WIDTH-1:0]   input0   [0:N-1];
    reg [Q_WIDTH-1:0]   input1   [0:N-1];
    reg [Q_WIDTH-1:0]   ntt_exp0 [0:N-1];
    reg [Q_WIDTH-1:0]   ntt_exp1 [0:N-1];
    reg [Q_WIDTH-1:0]   intt_exp0[0:N-1];
    reg [Q_WIDTH-1:0]   intt_exp1[0:N-1];

    // Capture read-back
    reg [Q_WIDTH-1:0]   hw_ntt0  [0:N-1];
    reg [Q_WIDTH-1:0]   hw_ntt1  [0:N-1];
    reg [Q_WIDTH-1:0]   hw_intt0 [0:N-1];
    reg [Q_WIDTH-1:0]   hw_intt1 [0:N-1];

    // ── Task: wait for done ───────────────────────────────────────
    integer guard_max;
    integer gi;
    task wait_done;
        begin
            guard_max = 4 * N * LOGN + 2 * N + 200;
            for (gi = 0; gi < guard_max; gi = gi + 1) begin
                @(posedge clk);
                if (done) gi = guard_max; // exit loop
            end
        end
    endtask

    // ── Task: compare lane results ────────────────────────────────
    integer fail_count;
    task compare;
        input integer lane;
        input [Q_WIDTH-1:0] got   [0:N-1];
        input [Q_WIDTH-1:0] exp   [0:N-1];
        input [63:0] tag;   // 0=NTT, 1=INTT
        integer ci;
        begin
            for (ci = 0; ci < N; ci = ci + 1) begin
                if (got[ci] !== exp[ci]) begin
                    $display("  FAIL %s lane=%0d i=%0d  got=%0d  exp=%0d",
                             tag ? "INTT" : "NTT ", lane, ci, got[ci], exp[ci]);
                    fail_count = fail_count + 1;
                end
            end
        end
    endtask

    // ── Main test ─────────────────────────────────────────────────
    integer i;
    integer lane;

    initial begin
        // ── Load test vectors ─────────────────────────────────────
        $readmemh("tv_rns_params_lane0.hex",       params0);
        $readmemh("tv_rns_params_lane1.hex",       params1);
        $readmemh("tv_rns_twiddles_fwd_lane0.hex", tw_fwd0);
        $readmemh("tv_rns_twiddles_inv_lane0.hex", tw_inv0);
        $readmemh("tv_rns_twiddles_fwd_lane1.hex", tw_fwd1);
        $readmemh("tv_rns_twiddles_inv_lane1.hex", tw_inv1);
        $readmemh("tv_rns_input_lane0.hex",        input0);
        $readmemh("tv_rns_input_lane1.hex",        input1);
        $readmemh("tv_rns_ntt_lane0.hex",          ntt_exp0);
        $readmemh("tv_rns_ntt_lane1.hex",          ntt_exp1);
        $readmemh("tv_rns_intt_lane0.hex",         intt_exp0);
        $readmemh("tv_rns_intt_lane1.hex",         intt_exp1);

        // ── Reset ─────────────────────────────────────────────────
        clk = 0; rst_n = 0;
        coeff_wr_en = 0; tw_wr_en = 0; start = 0; inverse = 0;
        repeat(8) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ── Assemble packed moduli buses ──────────────────────────
        // q_all:         lane1 q at [79:40], lane0 q at [39:0]
        // n_inv_all:     same layout
        
        
        q_all        = {params1[0][Q_WIDTH-1:0],   params0[0][Q_WIDTH-1:0]};
        n_inv_all    = {params1[1][Q_WIDTH-1:0],   params0[1][Q_WIDTH-1:0]};
        q_neg_inv_all= {params1[2][63:0], params0[2][63:0]};

        $display("Lane 0: q=%0d (%0d-bit)", params0[0][Q_WIDTH-1:0], $clog2(params0[0][Q_WIDTH-1:0])+1);
        $display("Lane 1: q=%0d (%0d-bit)", params1[0][Q_WIDTH-1:0], $clog2(params1[0][Q_WIDTH-1:0])+1);

        // ── Load twiddle tables ───────────────────────────────────
        // Lane 0
        tw_lane_sel = 0;
        for (i = 0; i < N; i = i + 1) begin tw_wr_en=1; tw_wr_addr=i;   tw_wr_data=tw_fwd0[i]; @(posedge clk); end
        for (i = 0; i < N; i = i + 1) begin              tw_wr_addr=N+i; tw_wr_data=tw_inv0[i]; @(posedge clk); end
        // Lane 1
        tw_lane_sel = 1;
        for (i = 0; i < N; i = i + 1) begin tw_wr_addr=i;   tw_wr_data=tw_fwd1[i]; @(posedge clk); end
        for (i = 0; i < N; i = i + 1) begin tw_wr_addr=N+i; tw_wr_data=tw_inv1[i]; @(posedge clk); end
        tw_wr_en = 0;
        @(posedge clk);

        // ── Load input coefficients ───────────────────────────────
        lane_sel=0; coeff_wr_en=1;
        for (i=0; i<N; i=i+1) begin coeff_wr_addr=i; coeff_wr_data=input0[i]; @(posedge clk); end
        lane_sel=1;
        for (i=0; i<N; i=i+1) begin coeff_wr_addr=i; coeff_wr_data=input1[i]; @(posedge clk); end
        coeff_wr_en=0; @(posedge clk);

        // ── Start NTT (both lanes fire simultaneously) ────────────
        $display("\n[NTT] Starting both lanes...");
        inverse = 0; start = 1; @(posedge clk); start = 0;
        wait_done;
        $display("[NTT] Done. lane_done=%b", lane_done);

        // ── Read back NTT results per lane ────────────────────────
        rd_lane=0; for (i=0;i<N;i=i+1) begin rd_addr=i; @(posedge clk); hw_ntt0[i]=rd_data; end
        rd_lane=1; for (i=0;i<N;i=i+1) begin rd_addr=i; @(posedge clk); hw_ntt1[i]=rd_data; end

        // ── Compare NTT per lane ──────────────────────────────────
        fail_count = 0;
        compare(0, hw_ntt0, ntt_exp0, 0);
        compare(1, hw_ntt1, ntt_exp1, 0);
        if (fail_count == 0)
            $display("[NTT] PASS — both lanes match expected");
        else
            $display("[NTT] FAIL — %0d mismatches", fail_count);

        // ── Reload NTT output as INTT input ──────────────────────
        lane_sel=0; coeff_wr_en=1;
        for (i=0;i<N;i=i+1) begin coeff_wr_addr=i; coeff_wr_data=hw_ntt0[i]; @(posedge clk); end
        lane_sel=1;
        for (i=0;i<N;i=i+1) begin coeff_wr_addr=i; coeff_wr_data=hw_ntt1[i]; @(posedge clk); end
        coeff_wr_en=0; @(posedge clk);

        // ── Start INTT (both lanes simultaneously) ────────────────
        $display("\n[INTT] Starting both lanes...");
        inverse = 1; start = 1; @(posedge clk); start = 0;
        wait_done;
        $display("[INTT] Done. lane_done=%b", lane_done);

        // ── Read back INTT results per lane ───────────────────────
        rd_lane=0; for (i=0;i<N;i=i+1) begin rd_addr=i; @(posedge clk); hw_intt0[i]=rd_data; end
        rd_lane=1; for (i=0;i<N;i=i+1) begin rd_addr=i; @(posedge clk); hw_intt1[i]=rd_data; end

        // ── Compare INTT per lane ─────────────────────────────────
        fail_count = 0;
        compare(0, hw_intt0, intt_exp0, 1);
        compare(1, hw_intt1, intt_exp1, 1);
        if (fail_count == 0)
            $display("[INTT] PASS — both lanes recovered original input");
        else
            $display("[INTT] FAIL — %0d mismatches", fail_count);

        $display("\nDone.");
        $finish;
    end

endmodule
