// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vrns_hash_verifier.h for the primary calling header

#ifndef VERILATED_VRNS_HASH_VERIFIER_HASH_VERIFIER_H_
#define VERILATED_VRNS_HASH_VERIFIER_HASH_VERIFIER_H_  // guard

#include "verilated.h"


class Vrns_hash_verifier__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vrns_hash_verifier_hash_verifier final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ clk;
        CData/*0:0*/ rst_n;
        CData/*1:0*/ ct_id;
        CData/*1:0*/ ct_sel;
        CData/*0:0*/ ct_wr_en;
        CData/*0:0*/ r_wr_en;
        CData/*0:0*/ tw_wr_en;
        CData/*1:0*/ c1_count;
        CData/*1:0*/ c2_count;
        CData/*1:0*/ c3_count;
        CData/*0:0*/ start;
        CData/*0:0*/ done;
        CData/*0:0*/ valid;
        CData/*0:0*/ __PVT__ch_ct_wr_en;
        CData/*1:0*/ __PVT__ch_ct_sel;
        CData/*0:0*/ __PVT__ch_r_wr_en;
        CData/*1:0*/ __PVT__ch_ct_count;
        CData/*0:0*/ __PVT__ch_start;
        CData/*0:0*/ __PVT__ch_done;
        CData/*0:0*/ __PVT__pm_a_wr_en;
        CData/*0:0*/ __PVT__pm_b_wr_en;
        CData/*0:0*/ __PVT__pm_start;
        CData/*0:0*/ __PVT__pm_done;
        CData/*0:0*/ __PVT__pa_a_wr_en;
        CData/*0:0*/ __PVT__pa_b_wr_en;
        CData/*0:0*/ __PVT__pa_start;
        CData/*0:0*/ __PVT__pa_done;
        CData/*3:0*/ __PVT__state;
        CData/*1:0*/ __PVT__comp_i;
        CData/*0:0*/ __PVT__cmp_ok;
        CData/*0:0*/ __PVT__u_ch__DOT__pm_a_wr_en;
        CData/*0:0*/ __PVT__u_ch__DOT__pm_b_wr_en;
        CData/*0:0*/ __PVT__u_ch__DOT__pm_start;
        CData/*0:0*/ __PVT__u_ch__DOT__pm_done;
        CData/*0:0*/ __PVT__u_ch__DOT__pa_a_wr_en;
        CData/*0:0*/ __PVT__u_ch__DOT__pa_b_wr_en;
        CData/*0:0*/ __PVT__u_ch__DOT__pa_start;
        CData/*0:0*/ __PVT__u_ch__DOT__pa_done;
        CData/*3:0*/ __PVT__u_ch__DOT__state;
        CData/*1:0*/ __PVT__u_ch__DOT__horner_i;
        CData/*1:0*/ __PVT__u_ch__DOT__ct_last;
        CData/*0:0*/ __PVT__u_ch__DOT__memr_we;
        CData/*0:0*/ __PVT__u_ch__DOT__memh_we;
        CData/*2:0*/ __PVT__u_ch__DOT__u_pmul__DOT__state;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_coeff_wr_en;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_start;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_inverse;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_done;
        CData/*0:0*/ u_ch__DOT__u_pmul__DOT____Vcellinp__u_ntt__coeff_wr_en;
        CData/*3:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__state;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__inv_r;
        CData/*0:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__cwe;
        CData/*1:0*/ __PVT__u_ch__DOT__u_padd__DOT__state;
        CData/*0:0*/ __PVT__u_ch__DOT__u_padd__DOT__wvalid;
        CData/*0:0*/ __PVT__u_ch__DOT__u_padd__DOT__sub_r;
        CData/*2:0*/ __PVT__u_pmul__DOT__state;
        CData/*0:0*/ __PVT__u_pmul__DOT__ntt_coeff_wr_en;
        CData/*0:0*/ __PVT__u_pmul__DOT__ntt_start;
        CData/*0:0*/ __PVT__u_pmul__DOT__ntt_inverse;
        CData/*0:0*/ __PVT__u_pmul__DOT__ntt_done;
        CData/*0:0*/ u_pmul__DOT____Vcellinp__u_ntt__coeff_wr_en;
        CData/*3:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__state;
        CData/*0:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__inv_r;
        CData/*0:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__cwe;
    };
    struct {
        CData/*1:0*/ __PVT__u_padd__DOT__state;
        CData/*0:0*/ __PVT__u_padd__DOT__wvalid;
        CData/*0:0*/ __PVT__u_padd__DOT__sub_r;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__8__comp;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__9__comp;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__40__comp;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__41__comp;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__72__comp;
        CData/*1:0*/ __Vfunc_u_ch__DOT__ct_lin__73__comp;
        CData/*0:0*/ __Vdly__pm_start;
        CData/*0:0*/ __Vdly__u_ch__DOT__pm_start;
        CData/*2:0*/ __Vdly__u_ch__DOT__u_pmul__DOT__state;
        CData/*2:0*/ __Vdly__u_pmul__DOT__state;
        CData/*0:0*/ __Vdly__u_ch__DOT__u_pmul__DOT__ntt_done;
        CData/*0:0*/ __Vdly__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__inv_r;
        CData/*0:0*/ __Vdly__u_pmul__DOT__ntt_done;
        CData/*0:0*/ __Vdly__u_pmul__DOT__u_ntt__DOT__inv_r;
        CData/*0:0*/ __VdlySet__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__coeff__v0;
        CData/*0:0*/ __VdlySet__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__tw__v0;
        CData/*0:0*/ __VdlySet__u_pmul__DOT__u_ntt__DOT__coeff__v0;
        CData/*0:0*/ __VdlySet__u_pmul__DOT__u_ntt__DOT__tw__v0;
        SData/*12:0*/ ct_wr_addr;
        SData/*12:0*/ r_wr_addr;
        SData/*13:0*/ tw_wr_addr;
        SData/*12:0*/ __PVT__ch_ct_wr_addr;
        SData/*12:0*/ __PVT__ch_r_wr_addr;
        SData/*12:0*/ __PVT__ch_rd_addr;
        SData/*12:0*/ __PVT__pm_a_wr_addr;
        SData/*12:0*/ __PVT__pm_b_wr_addr;
        SData/*12:0*/ __PVT__pm_rd_addr;
        SData/*12:0*/ __PVT__pa_a_wr_addr;
        SData/*12:0*/ __PVT__pa_b_wr_addr;
        SData/*12:0*/ __PVT__pa_rd_addr;
        SData/*13:0*/ __PVT__idx;
        SData/*12:0*/ __PVT__u_ch__DOT__pm_a_wr_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__pm_b_wr_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__pm_rd_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__pa_a_wr_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__pa_b_wr_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__pa_rd_addr;
        SData/*13:0*/ __PVT__u_ch__DOT__idx;
        SData/*12:0*/ __PVT__u_ch__DOT__ct_ra;
        SData/*12:0*/ __PVT__u_ch__DOT__memr_wa;
        SData/*12:0*/ __PVT__u_ch__DOT__memh_wa;
        SData/*13:0*/ __PVT__u_ch__DOT__u_pmul__DOT__idx;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_coeff_wr_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__int_rd_addr;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__stage;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__k;
        SData/*13:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__sc_idx;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__grp;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__ua;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__va;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__craddr;
        SData/*12:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__cwaddr;
        SData/*13:0*/ __PVT__u_ch__DOT__u_padd__DOT__cnt;
        SData/*12:0*/ __PVT__u_ch__DOT__u_padd__DOT__widx;
        SData/*12:0*/ __PVT__u_ch__DOT__u_padd__DOT__radr;
        SData/*13:0*/ __PVT__u_pmul__DOT__idx;
        SData/*12:0*/ __PVT__u_pmul__DOT__ntt_coeff_wr_addr;
        SData/*12:0*/ __PVT__u_pmul__DOT__int_rd_addr;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__stage;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__k;
        SData/*13:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__sc_idx;
    };
    struct {
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__grp;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__ua;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__va;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__craddr;
        SData/*12:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__cwaddr;
        SData/*13:0*/ __PVT__u_padd__DOT__cnt;
        SData/*12:0*/ __PVT__u_padd__DOT__widx;
        SData/*12:0*/ __PVT__u_padd__DOT__radr;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__8__a;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__9__a;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__40__a;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__41__a;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__72__a;
        SData/*12:0*/ __Vfunc_u_ch__DOT__ct_lin__73__a;
        SData/*13:0*/ __Vdly__u_ch__DOT__u_pmul__DOT__idx;
        SData/*13:0*/ __Vdly__u_pmul__DOT__idx;
        SData/*12:0*/ __Vdly__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__stage;
        SData/*12:0*/ __Vdly__u_pmul__DOT__u_ntt__DOT__stage;
        SData/*12:0*/ __VdlyDim0__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__coeff__v0;
        SData/*13:0*/ __VdlyDim0__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__tw__v0;
        SData/*12:0*/ __VdlyDim0__u_pmul__DOT__u_ntt__DOT__coeff__v0;
        SData/*13:0*/ __VdlyDim0__u_pmul__DOT__u_ntt__DOT__tw__v0;
        VlWide<3>/*79:0*/ barrett_m;
        VlWide<3>/*79:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mod_mul__Vstatic__p;
        VlWide<5>/*159:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mod_mul__Vstatic__pm;
        VlWide<3>/*79:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mod_mul__Vstatic__tq;
        VlWide<3>/*79:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mod_mul__Vstatic__r;
        VlWide<3>/*79:0*/ __PVT__u_pmul__DOT__mod_mul__Vstatic__p;
        VlWide<5>/*159:0*/ __PVT__u_pmul__DOT__mod_mul__Vstatic__pm;
        VlWide<3>/*79:0*/ __PVT__u_pmul__DOT__mod_mul__Vstatic__tq;
        VlWide<3>/*79:0*/ __PVT__u_pmul__DOT__mod_mul__Vstatic__r;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__8__Vfuncout;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__9__Vfuncout;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__40__Vfuncout;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__41__Vfuncout;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__72__Vfuncout;
        IData/*31:0*/ __Vfunc_u_ch__DOT__ct_lin__73__Vfuncout;
        QData/*39:0*/ __Vlvbound_hf311d938__0;
        QData/*39:0*/ q;
        QData/*39:0*/ n_inv;
        QData/*39:0*/ ct_wr_data;
        QData/*39:0*/ r_wr_data;
        QData/*39:0*/ tw_wr_data;
        QData/*39:0*/ __PVT__h3_rd;
        QData/*39:0*/ __PVT__ch_ct_wr_data;
        QData/*39:0*/ __PVT__ch_r_wr_data;
        QData/*39:0*/ __PVT__ch_rd_data;
        QData/*39:0*/ __PVT__pa_a_wr_data;
        QData/*39:0*/ __PVT__pa_rd_data;
        QData/*39:0*/ __PVT__h1_rd;
        QData/*39:0*/ __PVT__h2_rd;
        QData/*39:0*/ u_ch__DOT____Vlvbound_h7d40fc66__0;
        QData/*39:0*/ __PVT__u_ch__DOT__pa_a_wr_data;
        QData/*39:0*/ __PVT__u_ch__DOT__pa_rd_data;
        QData/*39:0*/ __PVT__u_ch__DOT__ct_rd;
        QData/*39:0*/ __PVT__u_ch__DOT__memr_rd;
        QData/*39:0*/ __PVT__u_ch__DOT__memh_rd;
        QData/*39:0*/ __PVT__u_ch__DOT__memr_wd;
        QData/*39:0*/ __PVT__u_ch__DOT__memh_wd;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mem_ntt_rd;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mem_b_wd;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__ntt_coeff_wr_data;
        QData/*40:0*/ __PVT__u_ch__DOT__u_pmul__DOT__mod_mul__Vstatic__t;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__cdo;
    };
    struct {
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__tdo;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__u_r;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__v_r;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__w_r;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__ct_u;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__gs_u;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__gs_v;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__scaled;
        QData/*39:0*/ __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__cwdata;
        QData/*39:0*/ __PVT__u_ch__DOT__u_padd__DOT__a_rd;
        QData/*39:0*/ __PVT__u_ch__DOT__u_padd__DOT__b_rd;
        QData/*39:0*/ __PVT__u_pmul__DOT__mem_ntt_rd;
        QData/*39:0*/ __PVT__u_pmul__DOT__mem_b_wd;
        QData/*39:0*/ __PVT__u_pmul__DOT__ntt_coeff_wr_data;
        QData/*40:0*/ __PVT__u_pmul__DOT__mod_mul__Vstatic__t;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__cdo;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__tdo;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__u_r;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__v_r;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__w_r;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__ct_u;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__gs_u;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__gs_v;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__scaled;
        QData/*39:0*/ __PVT__u_pmul__DOT__u_ntt__DOT__cwdata;
        QData/*39:0*/ __PVT__u_padd__DOT__a_rd;
        QData/*39:0*/ __PVT__u_padd__DOT__b_rd;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__12__Vfuncout;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__12__a;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__12__b;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__12__qq;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__22__Vfuncout;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__22__a;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__22__b;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__22__qq;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__44__Vfuncout;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__44__a;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__44__b;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__44__qq;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__54__Vfuncout;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__54__a;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__54__b;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__54__qq;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__76__Vfuncout;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__76__a;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__76__b;
        QData/*39:0*/ __Vfunc_u_ch__DOT__u_pmul__DOT__mod_mul__76__qq;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__86__Vfuncout;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__86__a;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__86__b;
        QData/*39:0*/ __Vfunc_u_pmul__DOT__mod_mul__86__qq;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_2;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_3;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_7;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_8;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_12;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_13;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_17;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_18;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_22;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_23;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_27;
        QData/*40:0*/ __VdfgRegularize_hebeb780c_0_28;
        QData/*39:0*/ __VdlyVal__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__coeff__v0;
    };
    struct {
        QData/*39:0*/ __VdlyVal__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__tw__v0;
        QData/*39:0*/ __VdlyVal__u_pmul__DOT__u_ntt__DOT__coeff__v0;
        QData/*39:0*/ __VdlyVal__u_pmul__DOT__u_ntt__DOT__tw__v0;
        VlUnpacked<QData/*39:0*/, 73728> __PVT__ct_mem;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__h1;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__h2;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__h3;
        VlUnpacked<QData/*39:0*/, 24576> __PVT__u_ch__DOT__ct;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__mem_r;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__mem_h;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_pmul__DOT__mem_b;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_pmul__DOT__mem_ntt;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__coeff;
        VlUnpacked<QData/*39:0*/, 16384> __PVT__u_ch__DOT__u_pmul__DOT__u_ntt__DOT__tw;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_padd__DOT__mem_a;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_padd__DOT__mem_b;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_ch__DOT__u_padd__DOT__mem_r;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_pmul__DOT__mem_b;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_pmul__DOT__mem_ntt;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_pmul__DOT__u_ntt__DOT__coeff;
        VlUnpacked<QData/*39:0*/, 16384> __PVT__u_pmul__DOT__u_ntt__DOT__tw;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_padd__DOT__mem_a;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_padd__DOT__mem_b;
        VlUnpacked<QData/*39:0*/, 8192> __PVT__u_padd__DOT__mem_r;
    };

    // INTERNAL VARIABLES
    Vrns_hash_verifier__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vrns_hash_verifier_hash_verifier();
    ~Vrns_hash_verifier_hash_verifier();
    void ctor(Vrns_hash_verifier__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(Vrns_hash_verifier_hash_verifier);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
